### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by aikd101** [TahaMalas/flutter_image_viewer#3]
![Screen Shot 2020-12-07 at 5 32 56 PM](https://user-images.githubusercontent.com/57030712/101334037-50734d80-38b2-11eb-856e-8ef72f5cb72d.png)

**Comment by rahmanrezaee** [comment]
I also face to this error

**Comment by aikd101** [comment]
oh i see. I thought i was the only one having this problem.

**Comment by iamvivekkaushik** [comment]
Does anyone have any idea on how to fix this?

**Comment by iamvivekkaushik** [comment]
FrescoImageView is no longer supported, I request the owner to migrate the project to https://github.com/stfalcon-studio/StfalconImageViewer or any other library.

**Comment by aikd101** [comment]
> Does anyone have any idea on how to fix this?

No one so far!

**Comment by TahaMalas** [comment]
Thanks for opening up an issue.

The problem is not from the package itself, it's because of the style theme you're using for your android app, sorry for not clearing that up in the documentation for the package.

To fix this issue, first open up `android/app/src/main/res/values/styles.xml` edit the parent of the `LaunchTheme` and put this value `Theme.AppCompat.Light.DarkActionBar`.

Now make sure you in `android/app/src/main/AndroidManifest.xml` the `.MainActivity` theme is set to `@style/LaunchTheme`

You have to stop the application and re-run it again.

This should solve the issue, please re-open it if the problem is still present.
