### ISSUE TITLE
http image support

### ISSUE THREAD

**Issue by zlmac** [TahaMalas/flutter_image_viewer#4]
not works on http images

**Comment by TahaMalas** [comment]
It should work as expected, you have to make sure you are using `clear text traffic` for HTTP requests with Android starting from Android 9.0 Pie.

You can make use of [this article](https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6) for that purpose.

If the issue is still present please feel free to re-open this issue.

Cheers,
